
/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientServer;

import static java.lang.String.valueOf;
import java.text.DecimalFormat;
import java.util.*;
import javafx.application.Application;
/**
 *
 * @author nivee
 */
class Graph {
    public static void beginGraph() {
        System.out.println("In Graph");
        Application.launch(Chart.class, new String[] {}); //method of calling the Application class to display the graph was adapted from Stack Overflow (https://stackoverflow.com/questions/25873769/launch-javafx-application-from-another-class)
    }
}
public class StationDataDisplayUI extends javax.swing.JFrame {

	
	public static HashMap<Integer, String[]> WSData = new HashMap<>();
    /**
     * Creates new form StationDataDisplayUI
     */

    public StationDataDisplayUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stationTitleLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        stationNoInput = new javax.swing.JTextField();
        cropLabel = new javax.swing.JLabel();
        humidityLabel = new javax.swing.JLabel();
        humidityInput = new javax.swing.JTextField();
        windLabel = new javax.swing.JLabel();
        windInput = new javax.swing.JTextField();
        precipitationInput = new javax.swing.JTextField();
        precipitationLabel = new javax.swing.JLabel();
        fieldNumBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        graphBtn = new javax.swing.JButton();
        stationDropBtn = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        latBox = new javax.swing.JTextField();
        lonBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stationTitleLabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        stationTitleLabel.setText("Station Data");

        backBtn.setBackground(new java.awt.Color(16, 91, 161));
        backBtn.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        backBtn.setForeground(new java.awt.Color(240, 240, 240));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        stationNoInput.setEditable(false);
        stationNoInput.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        stationNoInput.setText("example");

        cropLabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        cropLabel.setText("Station No:");
        cropLabel.setMaximumSize(new java.awt.Dimension(65, 15));

        humidityLabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        humidityLabel.setText("Humidity (%):");
        humidityLabel.setMaximumSize(new java.awt.Dimension(65, 15));
        humidityLabel.setPreferredSize(new java.awt.Dimension(65, 15));

        humidityInput.setEditable(false);
        humidityInput.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        humidityInput.setText("n");

        windLabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        windLabel.setText("Wind (mph):");
        windLabel.setMaximumSize(new java.awt.Dimension(65, 15));
        windLabel.setPreferredSize(new java.awt.Dimension(65, 15));

        windInput.setEditable(false);
        windInput.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        windInput.setText("n");
        windInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windInputActionPerformed(evt);
            }
        });

        precipitationInput.setEditable(false);
        precipitationInput.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        precipitationInput.setText("n");

        precipitationLabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        precipitationLabel.setText("Precipitation (%):");
        precipitationLabel.setMaximumSize(new java.awt.Dimension(65, 15));

        fieldNumBox.setEditable(false);
        fieldNumBox.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        jLabel1.setText("Field No:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(precipitationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(windLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(humidityLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cropLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldNumBox)
                    .addComponent(precipitationInput)
                    .addComponent(windInput)
                    .addComponent(humidityInput)
                    .addComponent(stationNoInput, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cropLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stationNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNumBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(humidityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(humidityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(windLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precipitationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precipitationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        graphBtn.setBackground(new java.awt.Color(7, 138, 59));
        graphBtn.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 13)); // NOI18N
        graphBtn.setForeground(new java.awt.Color(240, 240, 240));
        graphBtn.setText("View Graph");
        graphBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphBtnActionPerformed(evt);
            }
        });

        stationDropBtn.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        stationDropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationDropBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        jLabel2.setText("Latitude (Degree):");

        latBox.setEditable(false);
        latBox.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        lonBox.setEditable(false);
        lonBox.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        jLabel3.setText("Longtitude (Degree):");

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 13)); // NOI18N
        jLabel4.setText("GPS of Station");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap(485, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stationTitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stationDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(graphBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lonBox)
                    .addComponent(latBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(backBtn)
                .addGap(36, 36, 36)
                .addComponent(stationTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(stationDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(graphBtn)
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(latBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lonBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	
	
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        mainMenuUI menuScreen = new mainMenuUI();
        menuScreen.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void graphBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphBtnActionPerformed
        // TODO add your handling code here:
        Graph graph = new Graph();
        graph.beginGraph();
    }//GEN-LAST:event_graphBtnActionPerformed

    private void stationDropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationDropBtnActionPerformed
		Random RandGen = new  Random();
		Integer index = stationDropBtn.getSelectedIndex(); 
		index++;
		if(!(index == 0)){
			mainMenuUI.dataRequest = "WEATHER STATION,"+index;		
			mainMenuUI.buttonPressed = true;
			try{
				Thread.sleep(400);
			}
			catch(InterruptedException e){
				System.out.println(e.getMessage());
			}
			mainMenuUI.dataRequest = "";
			
			Integer fieldNum = (index-1) / 3;
			fieldNum++;
			
			double dLat = 51.942, dLon = -3.452;
			double lat = (RandGen.nextInt(100) + (fieldNum*100));
			double newLat = lat/10000;
			lat = dLat + newLat;
			double lon = (RandGen.nextInt(100) + (fieldNum*100));
			double newLon = lon/10000;
			lon = dLon + newLon;
                        DecimalFormat Rounded = new DecimalFormat("##.00000");
                        String latRounded = Rounded.format(lat);
                        String lonRounded = Rounded.format(lon);
			/*latBox.setText(valueOf(lat));
			lonBox.setText(valueOf(lon));*/
                        latBox.setText(latRounded);
                        lonBox.setText(lonRounded);

			
			fieldNumBox.setText(fieldNum.toString());
			stationNoInput.setText(index.toString());
			humidityInput.setText(WSData.get(index)[0]);
			windInput.setText(WSData.get(index)[1]);
			precipitationInput.setText(WSData.get(index)[2]);
		}
		
		
    }//GEN-LAST:event_stationDropBtnActionPerformed

    private void windInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_windInputActionPerformed

	public void fetchNumStations(){
		/*try{
			Thread.sleep(400);
		}
		catch(InterruptedException e){
			System.out.println(e.getMessage());
		}*/
		System.out.println(UserClient.numWeatherStations);
		for(int i = 0; i < UserClient.numWeatherStations; i++){
			stationDropBtn.addItem("Weather station " + (i+1));
			//WSData.put(i+1, String[] test);
		}
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StationDataDisplayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StationDataDisplayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StationDataDisplayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StationDataDisplayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StationDataDisplayUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel cropLabel;
    private javax.swing.JTextField fieldNumBox;
    private javax.swing.JButton graphBtn;
    public static javax.swing.JTextField humidityInput;
    private javax.swing.JLabel humidityLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField latBox;
    private javax.swing.JTextField lonBox;
    public static javax.swing.JTextField precipitationInput;
    private javax.swing.JLabel precipitationLabel;
    private javax.swing.JComboBox<String> stationDropBtn;
    public static javax.swing.JTextField stationNoInput;
    private javax.swing.JLabel stationTitleLabel;
    public static javax.swing.JTextField windInput;
    private javax.swing.JLabel windLabel;
    // End of variables declaration//GEN-END:variables
}
